# Available values options are available at https://github.com/grafana/alloy/blob/main/operations/helm/charts/alloy/values.yaml
global:
  image:
    registry: gsoci.azurecr.io

networkPolicy:
  flavor: cilium
  cilium:
    # Override Cilium Network Policy egress/ingress rules
    egress: []
    ingress: []

# Enable Kyverno PolicyException
kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm
  exceptions: []

alloy:
  # You can make the whole chart ineffective by setting enabled to "false"
  enabled: true

  alloy:
    extraArgs:
    # Disable reporting to GrafanaLabs
    - --disable-reporting

    extraSecretEnv: []

    mounts:
      # -- Extra volume mounts to add into the Grafana Alloy container.
      extra:
        # This is needed to allow alloy to create files when using readOnlyRootFilesystem
        - name: alloy-tmp
          mountPath: /tmp/alloy

    # -- Resource requests and limits to apply to the Grafana Alloy container.
    resources:
      limits:
        cpu: "1"
        memory: 256Mi
      requests:
        cpu: 25m
        memory: 128Mi

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsUser: 473
      runAsGroup: 473
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

  image:
    repository: giantswarm/alloy

  configReloader:
    image:
      repository: giantswarm/prometheus-config-reloader
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsUser: 473
      runAsGroup: 473
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

  controller:
    volumes:
      # -- Extra volumes to add to the Grafana Alloy pod.
      extra:
        - name: alloy-tmp
          emptyDir: {}

  serviceMonitor:
    enabled: true

verticalPodAutoscaler:
  # -- Creates a VerticalPodAutoscaler for the daemonset
  enabled: false

  # -- List of recommenders to use for the Vertical Pod Autoscaler.
  # Recommenders are responsible for generating recommendation for the object.
  # List should be empty (then the default recommender will generate the recommendation)
  # or contain exactly one recommender.
  recommenders: []
  # - name: custom-recommender-performance

  # -- Configures the resource policy for the Vertical Pod Autoscaler.
  resourcePolicy:
    # -- Configures the container policies for the Vertical Pod Autoscaler.
    containerPolicies:
    - containerName: alloy
      # -- The controlled resources for the Vertical Pod Autoscaler.
      controlledResources:
      - memory
      # -- The controlled values for the Vertical Pod Autoscaler. Needs to be either RequestsOnly or RequestsAndLimits.
      controlledValues: "RequestsAndLimits"
      # -- The maximum allowed values for the pods.
      maxAllowed: {}
      # cpu: 200m
      # memory: 100Mi
      # -- Defines the min allowed resources for the pod
      minAllowed: {}
      # cpu: 200m
      # memory: 100Mi

  # -- Configures the update policy for the Vertical Pod Autoscaler.
  updatePolicy:
    # -- Specifies minimal number of replicas which need to be alive for VPA Updater to attempt pod eviction
    # minReplicas: 1
    # -- Specifies whether recommended updates are applied when a Pod is started and whether recommended updates
    # are applied during the life of a Pod. Possible values are "Off", "Initial", "Recreate", and "Auto".
    # updateMode: Auto

# Creates PodLogs resources along Alloy
podLogs: []
