# Available values options are available at https://github.com/grafana/alloy/blob/main/operations/helm/charts/alloy/values.yaml
global:
  image:
    registry: gsoci.azurecr.io

networkPolicy:
  flavor: cilium
  cilium:
    # Override Cilium Network Policy egress/ingress rules
    egress: []
    ingress: []

# Enable Kyverno PolicyException
kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

alloy:
  # You can make the whole chart ineffective by setting enabled to "false"
  enabled: true

  alloy:
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: false
      runAsUser: 473
      runAsGroup: 473
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    extraSecretEnv: []

  image:
    repository: giantswarm/alloy

  configReloader:
    image:
      repository: giantswarm/configmap-reload
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsUser: 473
      runAsGroup: 473
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

  serviceMonitor:
    enabled: true
