{{- if and .Values.alloy.enabled .Values.additionalConfig.enabled }}
{{- if not (lookup "v1" "ConfigMap" .Release.Namespace (printf "%s-%s" (include "alloy.fullname" .) "additionalconfig")) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alloy.fullname" . }}-additionalconfig
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "alloy.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  config.alloy: |-
    {{- if .Values.additionalConfig.config }}
    {{ .Values.additionalConfig.config | nindent 4 }}
    {{- else }}
    declare "additional_config" {
      argument "forward_to" {
        optional = false
        comment  = "Where to send collected logs."
      }

      loki.source.kubernetes "default" {
        targets    = []
        forward_to = argument.forward_to.value
      }
    }
    {{- end }}
{{- end }}
{{- end }}
