{{- if .Values.kyvernoPolicyExceptions.enabled }}
{{- if .Capabilities.APIVersions.Has "kyverno.io/v2alpha1/PolicyException" -}}
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
  labels:
    {{- include "alloy.labels" . | nindent 4 }}
  name: {{ include "alloy.fullname" . }}
  namespace: {{ .Values.kyvernoPolicyExceptions.namespace | default .Release.Namespace }}
spec:
  exceptions:
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  - policyName: restrict-volume-types
    ruleNames:
    - restricted-volumes
    - autogen-restricted-volumes
{{- if not .Values.alloy.alloy.securityContext.runAsNonRoot }}
  - policyName: require-run-as-non-root-user
    ruleNames:
    - run-as-non-root-user
    - autogen-run-as-non-root-user
{{- end }}
  match:
    any:
    - resources:
        kinds:
        - Deployment
        - DaemonSet
        - StatefulSet
        - ReplicaSet
        - Pod
        namespaces:
        - {{ .Release.Namespace }}
        names:
        - {{ include "alloy.fullname" . }}*
{{- end -}}
{{- end -}}
