{{- range $podLog := .Values.podLogs }}
apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: {{ $podLog.name }}
  namespace: {{ $podLog.namespace }}
  labels:
    giantswarm.io/managed-by: logging-operator
  spec:
{{- $podLog.spec | toYaml | nindent 4 }}
{{- end }}
