{{- if .Values.alloy.alloy.extraSecretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alloy.fullname" . }}
  labels:
    {{- include "alloy.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  {{- range $secretEnvMap := .Values.alloy.alloy.extraSecretEnv }}
  {{ $secretEnvMap.name }}: {{ $secretEnvMap.value | b64enc }}
  {{- end }}
{{- end }}
