{{- if and (.Values.alloy.alloy.secret.create .Values.alloy.alloy.secret.content) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alloy.fullname" . }}
  labels:
    {{- include "alloy.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  {{- .Values.alloy.alloy.secret.content | nindent 2 }}
{{- end }}
