{{- if .Values.alloy.alloy.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alloy.fullname" . }}
  labels:
    {{- include "alloy.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  {{- if .Values.alloy.alloy.secret.content }}
  {{- .Values.alloy.alloy.secret.content | nindent 2 }}
  {{- else }}
  {{- .Files.Get "config/example.secret" | nindent 2 }}
  {{- end }}
{{- end }}
